title: suru.im
email: 33urus@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://suru.im"
github_username: suru33

# Build settings
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# plugins:
#   - jekyll-feed

# Search
search_enabled: true

# Footer
footer_content: "Copyright &copy; 2021-2022 Surendra Polam. Distributed by an <a href=\"/license\">MIT license.</a>"
last_edit_timestamp: true
last_edit_time_format: "%b %d, %Y at %H:%M" # https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
