title: suru.im
email: 33urus@gmail.com
description: SuRu's personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://suru.im"
github_username: suru33

# Build settings
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# plugins:
#   - jekyll-feed

# Search
search_enabled: true

# Footer
footer_content: "Copyright &copy; 2021-2022 SuRu.<br />Distributed by an <a href=\"/license\">MIT license.</a>"
last_edit_timestamp: true
last_edit_time_format: "%b %d, %Y at %H:%M" # https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/

aux_links:
  GitHub:
    - "//github.com/suru33"